return {
	Presets = {
		Casual = {
			IntermissionSeconds = 15,
			WarningSeconds = 5,
			WaveDurations = {40, 40, 40},
			WaveSpeeds = {1.2, 1.4, 1.6},
			CatchUpPerRound = 0.2,
			WaterStartY = -5,
			DeathZoneY = -50,
		},
		Sweaty = {
			IntermissionSeconds = 8,
			WarningSeconds = 3,
			WaveDurations = {30, 30, 30},
			WaveSpeeds = {1.8, 2.1, 2.4},
			CatchUpPerRound = 0.3,
			WaterStartY = -5,
			DeathZoneY = -50,
		},
	},
	Economy = {
		CoinsPerSecond = 10,
		SurvivalBonusPerWave = 150,
	},
	LuckyBlock = {
		BlockHealth = 3,
		SpawnCount = 20,
		RarityCoins = {
			Common = 50,
			Rare = 100,
			Epic = 150,
			Legendary = 200,
		},
		LootTable = {
			{item = "Grapple Hook", tier = "Rare", weight = 70, duration = 45},
			{item = "Rocket Boots", tier = "Epic", weight = 40, duration = 30},
			{item = "Glider Wings", tier = "Common", weight = 110, duration = 60},
			{item = "Dash Boots", tier = "Rare", weight = 75, duration = 35},
			{item = "Wall Climb Gloves", tier = "Rare", weight = 65, duration = 40},
			{item = "Hover Pack", tier = "Epic", weight = 38, duration = 25},
			{item = "Feather Fall", tier = "Common", weight = 105, duration = 50},
			{item = "Aegis Shield", tier = "Epic", weight = 42, duration = 20},
			{item = "Immunity Window", tier = "Legendary", weight = 15, duration = 15},
			{item = "Revive Token", tier = "Epic", weight = 35, duration = 0},
			{item = "Coin Magnet", tier = "Rare", weight = 80, duration = 30},
			{item = "Radar Goggles", tier = "Common", weight = 100, duration = 40},
			{item = "Platform Spawner", tier = "Rare", weight = 72, duration = 45},
			{item = "Time Slow", tier = "Legendary", weight = 12, duration = 8},
			{item = "Coin Doubler", tier = "Rare", weight = 70, duration = 40},
			{item = "Party Popper", tier = "Common", weight = 120, duration = 10},
			{item = "Rubber Ducky", tier = "Common", weight = 115, duration = 60},
			{item = "Neon Aura", tier = "Common", weight = 110, duration = 60},
			{item = "Risky Overdrive", tier = "Rare", weight = 55, duration = 25},
			{item = "Chaos Potion", tier = "Rare", weight = 50, duration = 30},
			{item = "Grapple v2", tier = "Epic", weight = 36, duration = 35},
			{item = "Speed Ramp Boost", tier = "Rare", weight = 68, duration = 40},
			{item = "Blink Teleport", tier = "Epic", weight = 38, duration = 20},
			{item = "Health Overshield", tier = "Common", weight = 108, duration = 50},
			{item = "Double Jump Extender", tier = "Common", weight = 112, duration = 45},
		},
	},
	Shop = {
		LootMagnet = {max = 5, costs = {300, 450, 675, 1012, 1518}, baseRadius = 20, maxRadius = 40},
		WalletExpansion = {max = 5, costs = {250, 375, 562, 843, 1264}, bonusPerLevel = 100},
		WalkSpeed = {max = 8, costs = {200, 300, 450, 675, 1012, 1518, 2277, 3415}, base = 16, perLevel = 1.5},
		JumpPower = {max = 6, costs = {220, 330, 495, 742, 1113, 1670}, base = 50, perLevel = 7.5},
		BreakSpeed = {max = 5, costs = {150, 225, 337, 506, 759}, baseHold = 0.3, minHold = 0.15},
		DailyReroll = {max = 3, costs = {400, 600, 900}},
	},
	Toasts = {
		Common = "⭐ Common power activated!",
		Rare = "✨ Rare find! You're lucky!",
		Epic = "💥 EPIC power-up! BIG advantage!",
		Legendary = "🌟 LEGENDARY! GAME CHANGER! 🌟",
	},
	RoundText = {
		Waiting = "Waiting for players...",
		Warning = "⚠️ WATER RISING ⚠️",
		Wave1 = "🌊 WAVE 1 OF 3 – WATER RISING!",
		Wave2 = "🌊 WAVE 2 OF 3 – PICK UP SPEED!",
		Wave3 = "🌊 FINAL WAVE! MAKE IT COUNT!",
		Victory = "✅ ROUND COMPLETE! +1,200 COINS!",
		Defeat = "💀 Drowned. Better luck next round.",
		AllEliminated = "💀 Everyone drowned. Round failed.",
	},
	Tutorial = {
		"The water is rising! Climb to escape.",
		"Break Lucky Blocks for power-ups and coins.",
		"Use tools smartly: grapple, dash, glide, climb.",
		"Survive each wave. Last player wins!",
		"Upgrade your skills in the Shop. Good luck! →",
	},
	Quests = {
		{
			id = "Q1",
			text = "Earn 2,000 coins in one session",
			reward = 300,
			difficulty = "Easy",
		},
		{
			id = "Q2",
			text = "Survive 3 full rounds without dying",
			reward = 400,
			difficulty = "Easy",
		},
		{
			id = "Q3",
			text = "Break 25 Lucky Blocks",
			reward = 250,
			difficulty = "Medium",
		},
		{
			id = "Q4",
			text = "Activate 5 Rare+ power-ups",
			reward = 350,
			difficulty = "Medium",
		},
		{
			id = "Q5",
			text = "Reach the Peak POI",
			reward = 150,
			difficulty = "Medium",
		},
		{
			id = "Q6",
			text = "Use Grapple 15 times",
			reward = 300,
			difficulty = "Hard",
		},
		{
			id = "Q7",
			text = "Survive Wave 3 without damage",
			reward = 500,
			difficulty = "Hard",
		},
		{
			id = "Q8",
			text = "Purchase 2 Shop upgrades",
			reward = 200,
			difficulty = "Meta",
		},
		{
			id = "Q9",
			text = "Play 5 rounds",
			reward = 250,
			difficulty = "Time sink",
		},
		{
			id = "Q10",
			text = "Equip 3 cosmetics simultaneously",
			reward = 100,
			difficulty = "Collect",
		},
		{
			id = "Q11",
			text = "Land a Legendary power-up and use it",
			reward = 600,
			difficulty = "Very Hard",
		},
		{
			id = "Q12",
			text = "Complete 4 other quests today",
			reward = 400,
			difficulty = "Grind",
		},
	},
}
