return {
	Tuning = {
		IntermissionSeconds = 20,
		WarningSeconds = 5,
		WaveDurations = {60, 45, 30},
		WaveRiseRates = {0.5, 1, 2},
		WaterStartY = -5,
	},
	Economy = {
		CoinsPerSecond = 1,
		BlockBreakBonus = 10,
		BaseSurvivalBonus = 150,
		WaveClearBonus = 100,
		RareItemBonus = 50,
	},
	Shop = {
		LootMagnet = {cost = 100, radius = 30},
		WalletExpansion = {cost = 150, bonus = 50},
		NimbleFeet = {cost = 200, speedPct = 0.15},
		HighJumper = {cost = 200, jumpPct = 0.2},
		BreakEfficiency = {cost = 250, reduceHits = 1},
		DailyReroll = {cost = 300, tokens = 1},
	},
	Loot = {
		RarityWeights = {
			Common = 40,
			Uncommon = 35,
			Rare = 20,
			Epic = 4,
		},
		RarityColors = {
			Common = Color3.fromRGB(255, 200, 80),
			Uncommon = Color3.fromRGB(80, 170, 255),
			Rare = Color3.fromRGB(200, 100, 255),
			Epic = Color3.fromRGB(255, 230, 160),
		},
		BlockHits = {
			Common = 3,
			Uncommon = 4,
			Rare = 6,
			Epic = 8,
		},
		Items = {
			Common = {
				{name = "+25 Coins", type = "Coins", amount = 25},
				{name = "+50 Coins", type = "Coins", amount = 50},
				{name = "+10 Coins", type = "Coins", amount = 10},
				{name = "Speed Burst", type = "Speed", multiplier = 1.25, duration = 10},
				{name = "Small Shield", type = "Shield", hits = 1},
				{name = "Double Loot Ticket", type = "DoubleLoot"},
			},
			Uncommon = {
				{name = "+100 Coins", type = "Coins", amount = 100},
				{name = "+75 Coins", type = "Coins", amount = 75},
				{name = "Speed Boost", type = "Speed", multiplier = 1.5, duration = 15},
				{name = "Jump Boost", type = "Jump", multiplier = 1.4, duration = 15},
				{name = "Medium Shield", type = "Shield", hits = 2},
				{name = "Loot Magnet Charm", type = "Magnet", radius = 50, duration = 5},
				{name = "Reroll Token", type = "Reroll"},
				{name = "Time Slow", type = "TimeSlow", slow = 0.5, duration = 8},
			},
			Rare = {
				{name = "+200 Coins", type = "Coins", amount = 200},
				{name = "+150 Coins", type = "Coins", amount = 150},
				{name = "Double Earnings", type = "CoinMultiplier", multiplier = 2},
				{name = "Invulnerable Potion", type = "Invuln", duration = 8},
				{name = "Heavy Shield", type = "Shield", hits = 5},
				{name = "Grapple Hook", type = "Mobility", speed = 1.25, jump = 1.2, duration = 12},
				{name = "Team Speedup", type = "TeamSpeed", radius = 40, multiplier = 1.3, duration = 10},
				{name = "Velocity Surge", type = "Mobility", speed = 1.4, jump = 2, duration = 10},
			},
			Epic = {
				{name = "+500 Coins", type = "Coins", amount = 500},
				{name = "Legendary Shield", type = "Shield", hits = 10},
				{name = "Time Freeze", type = "TimeSlow", slow = 0, duration = 10},
			},
		},
	},
	RoundText = {
		Waiting = "Waiting for players...",
		Warning = "⚠️ WATER RISING ⚠️",
		Wave1 = "🌊 WAVE 1 OF 3 – WATER RISING!",
		Wave2 = "🌊 WAVE 2 OF 3 – PICK UP SPEED!",
		Wave3 = "🌊 FINAL WAVE! MAKE IT COUNT!",
		Victory = "✅ ROUND COMPLETE! +150 COINS!",
		Defeat = "💀 Drowned. Better luck next round.",
		AllEliminated = "💀 Everyone drowned. Round failed.",
	},
	Tutorial = {
		"The water is rising! Climb to escape.",
		"Break Lucky Blocks for power-ups and coins.",
		"Use boosts smartly to reach higher ground.",
		"Survive each wave. Last player wins!",
		"Upgrade your skills in the Shop. Good luck! →",
	},
}
